### ISSUE TITLE
Synchronous API version

### ISSUE THREAD

**Issue by ghost** [c0b41/htmltidy2#12]
This is a very nice library, thanks a lot @c0b41 ,
I'm checking HTML formatting on small strings, I really would prefer a synchronous version of Tidy if there is a way?.

**Comment by Fdawgs** [comment]
Hey @bacloud22, in one of my projects I just [promisified Tidy](https://github.com/Fdawgs/docsmith/blob/master/src/plugins/tidy-html/index.js#L7) and then [`await`ed it](https://github.com/Fdawgs/docsmith/blob/master/src/plugins/tidy-html/index.js#L71) to make it synchronous.

**Comment by ghost** [comment]
Fastify as well 😄 very nice, it looks better but it looks synchronous (still async to my understanding).
Thanks a lot !

edit: So `htmltidy2` is a wrapper of another C/C++ library, and this is why it can't offer a synchronous API (I guess again @c0b41)
