### ISSUE TITLE
[URGENT] Incorrect access rights - Linux broken

### ISSUE THREAD

**Issue by kboshold** [c0b41/htmltidy2#23]
It seems that there is a problem with the access rights.  

What i did:
```bash
$ npm init
$ npm i -S htmltidy2
$ echo "var tidy = require('htmltidy2').tidy;
tidy('<table><tr><td>badly formatted html</tr>', function(err, html) {
    console.log(html);
});" > index.js
$ node index.js
```

Output:
```text
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy',
  path: '/home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy',
  spawnargs: [
    '--show-warnings',
    'no',
    '--tidy-mark',
    'no',
    '--force-output',
    'yes',
    '--quiet',
    'no'
  ]
}
```
Further Information:
```bash
$ ls -la /home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy
$ # -rw-rw-r--. 1 kpalatzky kpalatzky 1127960 Mar  9 10:14 /home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy
$ node -v
$ # v16.19.0
```

Local fix: 
```bash
$ chmod +x /home/kpalatzky/workspace/other/htmltidy2/node_modules/htmltidy2/bin/linux64/tidy
$ node index.js 
$ # <!DOCTYPE html> ..... (.. rest of the correct formatted html)
```

**Comment by kboshold** [comment]
It looks like a release issue to me: 

Git version:
```bash
$ git clone https://github.com/c0b41/htmltidy2.git
$ ls -la  htmltidy2/bin/linux64/tidy
$ # -rwxrwxr-x. 1 kpalatzky kpalatzky 1127960 Mar  9 12:35 htmltidy2/bin/linux64/tidy
$ # x is set and therefore executable
```

NPM version:
```bash
$ npm pack htmltidy2 --registry=https://registry.npmjs.org 
$ tar -xvf htmltidy2-1.0.1.tgz
$ ls -la package/bin/linux64/tidy 
$ # -rw-r--r--. 1 kpalatzky kpalatzky 1127960 Oct 26  1985 package/bin/linux64/tidy
$ # x is NOT set and therefore NOT executable
```

**Comment by c0b41** [comment]
I don't see any issue on my linux machine? maybe your setup doing something.. also all tests passing https://github.com/c0b41/htmltidy2/actions

**Comment by kboshold** [comment]
Thank you for the quick reply. I will test this on another machine, in a Docker image and on another network.

**Comment by kboshold** [comment]
@c0b41 i tested this now three different Systems:

- CentOS Stream release 8 => `Error: spawn /root/test/node_modules/htmltidy2/bin/linux64/tidy EACCES`
- Docker on CentOS Stream release 8 => `Error: spawn /root/test/node_modules/htmltidy2/bin/linux64/tidy EACCES`
- Ubuntu 20.04.5 LTS with new installed NodeJS 19 (NodeJS was not installed before) in a different Network => `Error: spawn /root/test/node_modules/htmltidy2/bin/linux64/tidy EACCES`

The error exists on all systems I have access to.  Can you try it yourself in a Docker container or clear your NPM cache if necessary. 

I also created a PR which checks if the executable is executable and if not makes it executable before. Since this also checks the existence via stat, this should ideally not be slower than the original solution.

**Comment by c0b41** [comment]
@kpalatzky yeah looks like npm doing something with binarys.. can you try with install github

```
"htmltidy2": "https://github.com/c0b41/htmltidy2.git#master"
```

**Comment by kboshold** [comment]
@c0b41 yes my guess is also that it must be NPM somehow. But since the TGZ itself already contains a non-executable file, it must be either "registry.npmjs.org" itself or the upload/release process (see comment above with the download of the TGZ file) - It cant be the local NPM tool. 

And yes with using the github link it works for me fine. That's unfortunately no way for use to use it that way, as it doesn't go through our security policies.

**Comment by c0b41** [comment]
I published new version, if still dosen't work for you you can pass your tidy binary. https://github.com/c0b41/htmltidy2#api

**Comment by kboshold** [comment]
@c0b41 It now works for me on all environments. Thank you!

**Comment by yanna92yar** [comment]
Hi,
Please allow me to follow up on this same issue. 
Also running the same version, and my binary is executable, so contrary to @kpalatzky I've run 

`chmod +x -R node_modules/htmltidy2/bin/`

and thus having an executable:

> /usr/src/app # ls -la /usr/src/app/node_modules/htmltidy2/bin/linux64/tidy
> -rwxr-xr-x    1 root     root       1127960 May 11 16:49 /usr/src/app/node_modules/htmltidy2/bin/linux64/tidy

With all this, it still raises another quite similar error:

> /usr/src/app # node index.js
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn /usr/src/app/node_modules/htmltidy2/bin/linux64/tidy ENOENT
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
>     at onErrorNT (node:internal/child_process:485:16)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
>     at onErrorNT (node:internal/child_process:485:16)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn /usr/src/app/node_modules/htmltidy2/bin/linux64/tidy',
>   path: '/usr/src/app/node_modules/htmltidy2/bin/linux64/tidy',
>   spawnargs: [
>     '--show-warnings',
>     'no',
>     '--tidy-mark',
>     'no',
>     '--force-output',
>     'yes',
>     '--quiet',
>     'no'
>   ]
> }

So, for me I'm having a file not found error while it is present.

Kindly.
