### ISSUE TITLE
Closing quotes of HTML elements' arguments

### ISSUE THREAD

**Issue by lazharichir** [c0b41/htmltidy2#8]
Is there any option to set so closing quotes can be fixed on arguments of HTML tags?

In other words, so this:
```
<img src="blah.png" alt="never closed the alternate text>
<p>Paragraph!</p>
```
Becomes this:
```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<img src="blah.png" alt="never closed the alternate text">
<p>Paragraph!</p>
</body>
</html>
```
Right now, it seems like the rest of the HTML is considered as a string so the `<p>Paragraph!</p>` is changed into HTML charges for the `>` and `<` characters.

**Comment by c0b41** [comment]
@lazharichir maybe help you http://api.html-tidy.org/tidy/tidylib_api_5.6.0/tidy_quickref.html
