### ISSUE TITLE
Update binaries from 5.6.0 to 5.8.0

### ISSUE THREAD

**Issue by Fdawgs** [c0b41/htmltidy2#9]
Hi there!

The binaries included are currently at 5.6.0, however these do not appear to work in Windows Server 2022.
The latest binaries, 5.8.0, do.

http://binaries.html-tidy.org/

Happy to open a PR, this would be a major bump though, as 5.6.0 had 32 bit binaries, whilst 5.8.0 does not.

**Comment by c0b41** [comment]
Yeah, send pull request..

**Comment by c0b41** [comment]
can you test out new canary version [1.0.0-canary.0](https://www.npmjs.com/package/htmltidy2/v/1.0.0-canary.0)

**Comment by Fdawgs** [comment]
Thanks @c0b41, have tested in Windows 10, Windows Server 2019, and Windows Server 2022 and it is now working as intended. 😄 

Seems to now be throwing an issue with Linux builds, however, though it may just be permissions:

```
node:events:498
   throw er; // Unhandled 'error' event
   ^

 Error: spawn /usr/app/node_modules/htmltidy2/bin/linux64/tidy EACCES
 at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
 at onErrorNT (node:internal/child_process:478:16)
 at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by c0b41** [comment]
interesting linux test passing https://github.com/c0b41/htmltidy2/pull/11/checks,

**Comment by Fdawgs** [comment]
No worries, just seems to be a permission issue on my end!

Edit: yep, was a permissions issue.

**Comment by tholu** [comment]
@Fdawgs Can you elaborate, on how you solved the permission issue?

**Comment by Fdawgs** [comment]
@tholu, sure:

https://github.com/Fdawgs/docsmith/blob/952f919eddc89e51ddb1bcbac59ba8f8a6f1a590/Dockerfile#L23-L24

**Comment by exentrich** [comment]
Same issue happen after clean install on macOS 13:
```
Error: spawn /Users/exentrich/Documents/Source/Repos/serverless/bookmarks-to-json/node_modules/htmltidy2/bin/darwin/tidy EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by c0b41** [comment]
I don't have any macos device so hard to test locally, test passing so  ı'm not sure what is happening.. https://github.com/c0b41/htmltidy2/actions/runs/3429823269/jobs/5715964975
